repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.5
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--config=./backend/ruff.toml", "./backend/src"]
      # Run the formatter.
      - id: ruff-format
        args: ["--config=./backend/ruff.toml", "./backend/src"]